version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    network_mode: "host"


#networks:
#    default:
#        name: mynetwork
#        driver: host